name: Checkov Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  checkov-scan:
    name: Run Checkov Scan on Specific Folder
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Python môi trường (Checkov yêu cầu Python)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Bước 3: Cài đặt Checkov qua pip
      - name: Install Checkov
        run: pip install checkov

      # Bước 4: Chạy Checkov để quét folder cụ thể
      - name: Run Checkov on 'terraform' folder
        run: checkov -d ./terraform